# Generated by Django 2.2.3 on 2019-07-08 01:00

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False # <<<< THIS LINE

    dependencies = [
        ('core', '0006_auto_20190707_2153'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='Talk',
        ),
    ]
